apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: Python-pipeline
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: Python-pipeline 
  name: Python-pipeline
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: Python-pipeline 
